import type { Metadata } from 'next'
import './globals.css'
import '../../public/lib/bootstrap/bootstrap.min.css';
import Navbar from './ui/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-light'>
        <Navbar />
        {children}</body>
    </html>
  )
}
